version: '3.9'
services:
  core:
    build: .
    command: mix phx.server
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq"
      REDIS_URL: "redis://redis:6379"
    networks:
      - konsi

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - konsi

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - konsi

networks:
  konsi:
    name: konsi
